### ISSUE TITLE
Allow to provide databast file path in command line interface

### ISSUE THREAD

**Issue by mlangkabel** [packdat/SourcetrailDotnetIndexer#1]
Currently the SourcetrailDotnetIndexer accepts the `-o` option, which can be used to provide an output directory and the database file name depends on the indexed assembly. This makes direct integration into Sourcetrail quite hard, because Sourcetrail's "Custom Source Group" needs to control the exact database file name (e.g. for multi threaded indexing databases are called `ProjectName.srctrldb_tmp_thread1` during indexing and afterwards they are merged into one large database).

Can we change the -o option, such that one can also provide a file name?

**Comment by packdat** [comment]
Thank you for the suggestion.
I would like to keep the `-o` option for the lazy ones like me.
As an alternative, i would suggest an additional option, (e.g. `-of c:\path\filename`) that would take precedence over the `-o` option.
Would that be sufficient for easier integration ?

**Comment by mlangkabel** [comment]
Sure! That would be great!
