### ISSUE TITLE
Unity C# Scripts

### ISSUE THREAD

**Issue by gotanidea** [packdat/SourcetrailDotnetIndexer#11]
Could the software be used for Unity C# scripts? I have tried the following steps:

1. Build _SourcetrailDotnetIndexer_ project without any error, using _Visual Studio Community 2022_ and the target framework is 4.7.1.

2. Find the locations of the framework assemblies, using `dotnet --list-runtimes` command. The results are:
_Microsoft.AspNetCore.App 6.0.1 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
Microsoft.NETCore.App 6.0.1 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
Microsoft.WindowsDesktop.App 6.0.1 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]_

3. Head over to the directory where the _SourcetrailDotnetIndexer.exe_ is located (_C:/Users/ISM/Downloads/SourcetrailDotnetIndexer/SourcetrailDotnetIndexer/bin/Debug_).

4. Run each of these commands:
`SourcetrailDotnetIndexer.exe -i D:\UnityProjects\2020\MyUnityProject\Library\ScriptAssemblies\Assembly-CSharp.dll -o . -s "C:\Program Files\dotnet\shared\Microsoft.NETCore.App\6.0.1"`
`SourcetrailDotnetIndexer.exe -i D:\UnityProjects\2020\MyUnityProject\Library\ScriptAssemblies\Assembly-CSharp.dll -o . -s "C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App\6.0.1"`
`SourcetrailDotnetIndexer.exe -i D:\UnityProjects\2020\MyUnityProject\Library\ScriptAssemblies\Assembly-CSharp.dll -o . -s "C:\Windows\Microsoft.NET\Framework64\v4.0.30319"`

I get the same error:
_An exception occurred:
System.TypeInitializationException: The type initializer for 'CoatiSoftware.SourcetrailDB.sourcetraildbPINVOKE' threw an exception. ---> System.TypeInitializationException: The type initializer for 'SWIGExceptionHelper' threw an exception. ---> System.BadImageFormatException: An attempt was made to load a program with an incorrect format. (Exception from HRESULT: 0x8007000B)
   at CoatiSoftware.SourcetrailDB.sourcetraildbPINVOKE.SWIGExceptionHelper.SWIGRegisterExceptionCallbacks_sourcetraildb(ExceptionDelegate applicationDelegate, ExceptionDelegate arithmeticDelegate, ExceptionDelegate divideByZeroDelegate, ExceptionDelegate indexOutOfRangeDelegate, ExceptionDelegate invalidCastDelegate, ExceptionDelegate invalidOperationDelegate, ExceptionDelegate ioDelegate, ExceptionDelegate nullReferenceDelegate, ExceptionDelegate outOfMemoryDelegate, ExceptionDelegate overflowDelegate, ExceptionDelegate systemExceptionDelegate)
   at CoatiSoftware.SourcetrailDB.sourcetraildbPINVOKE.SWIGExceptionHelper..cctor() in C:\Users\ISM\Downloads\SourcetrailDotnetIndexer\SourcetrailDotnetIndexer\Sourcetrail\sourcetraildbPINVOKE.cs:line 105
   --- End of inner exception stack trace ---
   at CoatiSoftware.SourcetrailDB.sourcetraildbPINVOKE.SWIGExceptionHelper..ctor()
   at CoatiSoftware.SourcetrailDB.sourcetraildbPINVOKE..cctor() in C:\Users\ISM\Downloads\SourcetrailDotnetIndexer\SourcetrailDotnetIndexer\Sourcetrail\sourcetraildbPINVOKE.cs:line 125
   --- End of inner exception stack trace ---
   at CoatiSoftware.SourcetrailDB.sourcetraildbPINVOKE.open(String jarg1)
   at CoatiSoftware.SourcetrailDB.sourcetraildb.open(String databaseFilePath) in C:\Users\ISM\Downloads\SourcetrailDotnetIndexer\SourcetrailDotnetIndexer\Sourcetrail\sourcetraildb.cs:line 34
   at SourcetrailDotnetIndexer.DataCollector..ctor(String outputFileName) in C:\Users\ISM\Downloads\SourcetrailDotnetIndexer\SourcetrailDotnetIndexer\DataCollector.cs:line 23
   at SourcetrailDotnetIndexer.SourcetrailDotnetIndexer.Index(String outputFileName) in C:\Users\ISM\Downloads\SourcetrailDotnetIndexer\SourcetrailDotnetIndexer\SourcetrailDotnetIndexer.cs:line 27
   at SourcetrailDotnetIndexer.Program.Main(String[] args) in C:\Users\ISM\Downloads\SourcetrailDotnetIndexer\SourcetrailDotnetIndexer\Program.cs:line 58_

**Comment by packdat** [comment]
That  sounds like you didn't specify "x64" as the target platform when compiling the indexer.
As the readme states:

> For convenience, the native DLL for SourcetrailDB is already included, so you don't have to build it yourself.
Note, the native DLL is a x64 DLL so in your project settings, you have to specify x64 as the target platform as well.

Please compile to x64 and try again
See also #8

**Comment by gotanidea** [comment]
Thanks for your reply. After changing the target platform, the _srctrldb_ and _srctrlprj_ files are generated, with this message:

`Indexing assembly D:\UnityProjects\2020\MyUnityProject\Library\ScriptAssemblies\Assembly-CSharp.dll`

`An exception occurred reading the debug-information from D:\UnityProjects\2020\MyUnityProject\Library\ScriptAssemblies\Assembly-CSharp.pdb
COMException -> Exception from HRESULT: 0x806D000C`
`Loaded: D:\UnityProjects\2020\MyUnityProject\Library\ScriptAssemblies\Assembly-CSharp.pdb
Collecting types...`
`Unable to resolve assembly UnityEngine.CoreModule, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null.`
`Hint: Specify additional assembly-locations using the -s switch.`
`Unable to resolve assembly UnityEngine.CoreModule, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null.`
`Hint: Specify additional assembly-locations using the -s switch.`
`Load: D:\UnityProjects\2020\MyUnityProject\Library\ScriptAssemblies\UnityEngine.UI.dll`
`Unable to resolve assembly UnityEngine.CoreModule, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null.`
`Hint: Specify additional assembly-locations using the -s switch.`
`Unable to resolve assembly UnityEngine.CoreModule, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null.`
`Hint: Specify additional assembly-locations using the -s switch.`
`Unable to resolve assembly UnityEngine.CoreModule, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null.`
`Hint: Specify additional assembly-locations using the -s switch.`
`Unable to resolve assembly UnityEngine.CoreModule, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null.`
`Hint: Specify additional assembly-locations using the -s switch.`
`Load: C:\Windows\Microsoft.NET\Framework64\v4.0.30319\netstandard.dll`
`Load: D:\UnityProjects\2020\MyUnityProject\Library\ScriptAssemblies\Unity.InputSystem.dll`
`Exception indexing assemby 'D:\UnityProjects\2020\MyUnityProject\Library\ScriptAssemblies\Assembly-CSharp.dll'`
`System.Reflection.ReflectionTypeLoadException: Unable to load one or more of the requested types. Retrieve the LoaderExceptions property for more information.`
   `at System.Reflection.RuntimeModule.GetTypes(RuntimeModule module)`
   `at System.Reflection.Assembly.GetTypes()`
   `at SourcetrailDotnetIndexer.SourcetrailDotnetIndexer.Index(String outputFileName) in C:\Users\ISM\Downloads\SourcetrailDotnetIndexer\SourcetrailDotnetIndexer\SourcetrailDotnetIndexer.cs:line 43`

`Collected 0 types`

`Parsing IL... (0 methods)`

`Sourcetrail database has been generated at .\Assembly-CSharp.srctrldb
Time taken: 00:00:00.3050620`

I use the following _Custom Command_ in the _Source Group_:
_"C:\Users\ISM\Downloads\SourcetrailDotnetIndexer\SourcetrailDotnetIndexer\bin\Debug\SourcetrailDotnetIndexer.exe" -i %{SOURCE_FILE_PATH} -s "C:\Windows\Microsoft.NET\Framework64\v4.0.30319"_

After the indexing, no files and errors are created. I think it doesn't work for Unity C# scripts or maybe I did something incorrectly.

**Comment by packdat** [comment]
If your code gets compiled into a valid .NET assembly, it should definitively work.
The main issue i see in the output is that the  assembly `UnityEngine.CoreModule` cannot be resolved.
Is this assembly located in the same folder as you script-assembly ?
(just wondering why other assemblies like `Unity.InputSystem.dll` ARE found)
Maybe it is sufficient to specify the location of the core Unity engine DLLs with an additional `-s` switch.

**Comment by gotanidea** [comment]
I gathered all DLLs into one folder and it just generated one exception this time:

`Indexing assembly C:\Users\ISM\Documents\Test\Assembly-CSharp.dll`

`An exception occurred reading the debug-information from C:\Users\ISM\Documents\Test\Assembly-CSharp.pdb
COMException -> Exception from HRESULT: 0x806D000C`
`Loaded: C:\Users\ISM\Documents\Test\Assembly-CSharp.pdb`
`Collecting types...`
`Load: C:\Users\ISM\Documents\Test\UnityEngine.CoreModule.dll`
`Load: C:\Users\ISM\Documents\Test\UnityEngine.UI.dll`
`Load: C:\Users\ISM\Documents\Test\UnityEngine.dll`
`Load: C:\Users\ISM\Documents\Test\Unity.InputSystem.dll`
`Load: C:\Users\ISM\Documents\Test\netstandard.dll`

`Collected 0 types`

`Parsing IL... (0 methods)`

`Sourcetrail database has been generated at .\Assembly-CSharp.srctrldb`
`Time taken: 00:00:00.3350550`

However, there is still no file indexed in Sourcetrail:

[https://ibb.co/sqQjnXY](url)

**Comment by packdat** [comment]
According to [this ](https://stackoverflow.com/questions/18374023/load-data-from-microsoft-pdb-file-using-dia-sdk) question on SO, the exception results from an unsupported PDB-format.
Are the PDBs generated by VisualStudio or does Unity has its own compiler ?
But as PDBs are optional and are only used to display source-information in Sourcetrail, this is not the main issue.
The main issues seems to be that the indexed assembly does not seem to have any types in it.
Are you able to share the assembly for analysis ?

**Comment by gotanidea** [comment]
> According to [this ](https://stackoverflow.com/questions/18374023/load-data-from-microsoft-pdb-file-using-dia-sdk) question on SO, the exception results from an unsupported PDB-format. Are the PDBs generated by VisualStudio or does Unity has its own compiler ? But as PDBs are optional and are only used to display source-information in Sourcetrail, this is not the main issue. The main issues seems to be that the indexed assembly does not seem to have any types in it. Are you able to share the assembly for analysis ?

Hi, I believe the PDBs are generated by Unity's compiler, not by Visual Studio. Please find the assembly (_ScriptableObject-Architecture.dll_) and the dependencies (_UnityEngine.CoreModule.dll_ and other DLL files) from this link:

[https://mega.nz/file/1M0yQA5C#mESFfwvYsZsGJBxFnZVkaVnciku8ll1S0yeFUWIJlxU](https://mega.nz/file/1M0yQA5C#mESFfwvYsZsGJBxFnZVkaVnciku8ll1S0yeFUWIJlxU)

In _Sourcetrail_, I drag the assembly (_ScriptableObject-Architecture.dll_) into the _Edit Project / Source Groups / Custom Command Source Group / Files & Directories to Index area_.

And here are the Visual Studio solution and the C# projects, inside the Unity project:

[https://mega.nz/file/ActC3ZJR#M5-5kk60M_hlhuiygMZZQzsTIP76t8TPIIwD8EudcJQ](https://mega.nz/file/ActC3ZJR#M5-5kk60M_hlhuiygMZZQzsTIP76t8TPIIwD8EudcJQ)

Thanks

**Comment by packdat** [comment]
Thanks for providing the assemblies, these helped identifying the issue.
The issue was that all types in **Assembly-CSharp.dll** were declared in the _global_ namespace i.e `type.Namespace` was `null`.
The indexer skipped these types, because these are typically compiler-generated classes which i deemed to be just _noise_.

I will add a command-line switch that allows including these types, should be ready in the next few days.

**Comment by gotanidea** [comment]
> Thanks for providing the assemblies, these helped identifying the issue. The issue was that all types in **Assembly-CSharp.dll** were declared in the _global_ namespace i.e `type.Namespace` was `null`. The indexer skipped these types, because these are typically compiler-generated classes which i deemed to be just _noise_.
> 
> I will add a command-line switch that allows including these types, should be ready in the next few days.

Thank you for the tool

**Comment by packdat** [comment]
I just released a version with the mentioned switch added.
Re-build the indexer from the latest sources or use the pre-build version from [here](https://github.com/packdat/SourcetrailDotnetIndexer/releases/tag/main-71e91c3c).

When running the indexer, you can now specify the `-ag` switch (short for *allow globals*) to also index types from the global namespace.
Please let me know, whether this resolves your issue.

**Comment by gotanidea** [comment]
> 

Thanks a lot! It works after adding the `-ag` switch.
