### ISSUE TITLE
Error: Unable to load DLL 'SourcetrailDB'

### ISSUE THREAD

**Issue by rjmr97** [packdat/SourcetrailDotnetIndexer#3]
Hey!

I've opened the .sln and compiled using x64, this does copy the SourcetrailDB.dll to the bin folder.
However, when I try to run it doesn't seem too find the dll or one of it's dependencies. Is there some other dlls I'm missing in my system?

I don't think this is a problem directly related to your project (I've seen others are able to run it), but maybe you could help me find the problem?

This is the command I'm running:
(ClassLibrary1.dll is just a project I created for testing, it's just a class and a method and it is compiled with x64)
```
> cd E:\sourcetrail-test\solution\SourcetrailDotnetIndexer\bin\x64\Debug

> SourcetrailDotnetIndexer.exe -i "E:\sourcetrail-test\assembly\ClassLibrary1.dll" -o "output"
```

And this is the error I get:
```
Unhandled Exception: System.TypeInitializationException: The type initializer for 'CoatiSoftware.SourcetrailDB.sourcetraildbPINVOKE' threw an exception. ---> System.TypeInitializationException: The type initializer for 'SWIGExceptionHelper' threw an exception. ---> System.DllNotFoundException: Unable to load DLL 'SourcetrailDB': The specified module could not be found. (Exception from HRESULT: 0x8007007E)
   at CoatiSoftware.SourcetrailDB.sourcetraildbPINVOKE.SWIGExceptionHelper.SWIGRegisterExceptionCallbacks_sourcetraildb(ExceptionDelegate applicationDelegate, ExceptionDelegate arithmeticDelegate, ExceptionDelegate divideByZeroDelegate, ExceptionDelegate indexOutOfRangeDelegate, ExceptionDelegate invalidCastDelegate, ExceptionDelegate invalidOperationDelegate, ExceptionDelegate ioDelegate, ExceptionDelegate nullReferenceDelegate, ExceptionDelegate outOfMemoryDelegate, ExceptionDelegate overflowDelegate, ExceptionDelegate systemExceptionDelegate)
   at CoatiSoftware.SourcetrailDB.sourcetraildbPINVOKE.SWIGExceptionHelper..cctor() in E:\sourcetrail-test\solution\SourcetrailDotnetIndexer\Sourcetrail\sourcetraildbPINVOKE.cs:line 105
   --- End of inner exception stack trace ---
   at CoatiSoftware.SourcetrailDB.sourcetraildbPINVOKE.SWIGExceptionHelper..ctor()
   at CoatiSoftware.SourcetrailDB.sourcetraildbPINVOKE..cctor() in E:\sourcetrail-test\solution\SourcetrailDotnetIndexer\Sourcetrail\sourcetraildbPINVOKE.cs:line 125
   --- End of inner exception stack trace ---
   at CoatiSoftware.SourcetrailDB.sourcetraildbPINVOKE.getVersionString()
   at CoatiSoftware.SourcetrailDB.sourcetraildb.getVersionString() in E:\sourcetrail-test\solution\SourcetrailDotnetIndexer\Sourcetrail\sourcetraildb.cs:line 15
   at SourcetrailDotnetIndexer.Program.Main(String[] args) in E:\sourcetrail-test\solution\SourcetrailDotnetIndexer\Program.cs:line 24
```

**Comment by packdat** [comment]
Hi !
So you're saying the SourcetraiDB.dll **is there** but the program crashes with the mentioned exception ?
That sounds strange to me...

Making a clean build and looking into the `/bin/x64/Debug` folder i find the following files:

- Microsoft.DiaSymReader.dll
- Microsoft.DiaSymReader.Native.amd64.dll
- Microsoft.DiaSymReader.Native.x86.dll
- Microsoft.DiaSymReader.pdb
- Microsoft.DiaSymReader.xml
- SourcetrailDB.dll
- SourcetrailDotnetIndexer.exe
- SourcetrailDotnetIndexer.exe.config
- SourcetrailDotnetIndexer.pdb

Navigating a PowerShell to this folder and executing the command
`.\SourcetrailDotnetIndexer.exe -i .\SourcetrailDotnetIndexer.exe -s C:\Windows\Microsoft.NET\Framework64\v4.0.30319 -o .`
successfully produced a database in the current directory.
If that does not work on your system, i have no idea, what could be wrong.

**Comment by rjmr97** [comment]
> So you're saying the SourcetraiDB.dll is there but the program crashes with the mentioned exception ?

Yes, exactly.

I made a short video showing what I'm doing, maybe you can see something I'm doing wrong?
https://user-images.githubusercontent.com/30321188/109303353-9517e080-7832-11eb-8eb4-97ca2f30797a.mp4

Also, do I need to have SWIG installed, or is it only needed when creating the DLL?

If nothing else works I may try to create the DLL myself...

**Comment by packdat** [comment]
Watching your video i cannot see any wrong-doing on your side.

> Also, do I need to have SWIG installed, or is it only needed when creating the DLL?

No, SWIG is only required, if you want to build the native SourcetrailDB.dll by yourself.

Until now, i have just blindly assumed, you're using a 64-bit OS, is that really the case ?
Open a PowerShell console and execute `(Get-WmiObject Win32_OperatingSystem).OSArchitecture`, it should print `64-bit`.
If it prints anything else, this might be the problem, as the native dll is explicitly compiled for x64.
If it **does** say, it's 64-bit, then it might be worth trying to build the dll by yourself, as i'm out of ideas here....

You could also try to download the [current release](https://github.com/packdat/SourcetrailDotnetIndexer/releases/tag/main-4a0023ec) available since yesterday and see, if that somehow behaves differently.

**Comment by rjmr97** [comment]
I'm running 64bit OS, but I ran the command just in case. This is the output:
```pwsh
PS C:\Users\rribeiro> (Get-WmiObject Win32_OperatingSystem).OSArchitecture
64-bit
```

Also tried the release you mentioned but I get the same error...
I will try and build the DLL on my side and see if that works.

I'm closing the issue because I really don't think it's a problem with your project.
If I do find the problem I'll post a comment as it might help someone else.

Thanks for trying to help!

**Comment by rjmr97** [comment]
Got it working!
Must have been some DLL dependency that was missing on my system (not sure which).

Installed "Desktop Development with C++" from Visual Studio Installer in order to compile the SourcetrailDB.dll myself.
Compiled it but decided to test yours again.... it worked.

```pwsh
PS E:\sourcetrail-test\SourcetrailDotnetIndexer\bin\x64\Debug> .\SourcetrailDotnetIndexer.exe -i .\SourcetrailDotnetIndexer.exe -s C:\Windows\Microsoft.NET\Framework64\v4.0.30319 -o .
Indexing assembly .\SourcetrailDotnetIndexer.exe

Loaded: E:\sourcetrail-test\SourcetrailDotnetIndexer\bin\x64\Debug\SourcetrailDotnetIndexer.pdb
Collecting types...
Load: .\Microsoft.DiaSymReader.dll
Load: C:\Windows\Microsoft.NET\Framework64\v4.0.30319\System.dll

Collected 30 types

Parsing IL... (202 methods)

Load: C:\Windows\Microsoft.NET\Framework64\v4.0.30319\System.Core.dll

Sourcetrail database has been generated at .\SourcetrailDotnetIndexer.srctrldb
Time taken: 00:00:04.1098021
```

**Comment by packdat** [comment]
Great, thank you for reporting back !
Now that you mentioned that, it makes totally sense.
Since the SourcetrailDB is a native dll it will probably depend on the VC-Runtime, which may not be present on every system.
I'll have to confirm which exact one is required and point that out in the Readme.
