### ISSUE TITLE
System.PlatformNotSupportedException: ReflectionOnly loading is not supported on this platform

### ISSUE THREAD

**Issue by gbtb** [packdat/SourcetrailDotnetIndexer#5]
Hello!
I was trying to use SourcetrailDotnetCoreIndexer to analyze some simple net5.0 console project, and got an exception while indexer tried to load dependency assemblies.

Looking through code, I've found related comment at [this file](https://github.com/packdat/SourcetrailDotnetIndexer/blob/c9b7a6674000fd59a1b5513416d03c4cff4b76e4/SourcetrailDotnetCoreIndexer/Program.cs#L44)
And after a bit of debugging, I've found the [place](https://github.com/packdat/SourcetrailDotnetIndexer/blob/c9b7a6674000fd59a1b5513416d03c4cff4b76e4/SourcetrailDotnetIndexer/Program.Shared.cs#L47) which causes an exception.
I've tried to replace calls of Assembly.ReflectionOnlyLoadFrom with Assembly.LoadFrom , and error has gone.
It looks to me, that simplest solution would be to create an overload of CurrentDomain_AssemblyResolve for DotnetCore indexer, which uses Assembly.LoadFrom. What do you think?

**Comment by packdat** [comment]
Hi !
Thanks for reporting this, i haven't tested extensively with net 5 assemblies yet.
And i think you're right, replacing the call to Assembly.ReflectionOnlyLoadFrom with Assembly.LoadFrom seems to be the simplest solution.
Another option would be to use a dedicated version of CurrentDomain_AssemblyResolve for each version; the DotnetIndexer could stick with Assembly.ReflectionOnlyLoadFrom while the DotnetcoreIndexer would use Assembly.LoadFrom.

**Comment by gbtb** [comment]
> Another option would be to use a dedicated version of CurrentDomain_AssemblyResolve for each version
I'd like this option more, it's always better to not break things which already works :) I will submit PR shortly.
