### ISSUE TITLE
Typer initializer for 'CoatiSoftware.SourcetrailDB.sourcetraildbPINVOKE' threw an exception

### ISSUE THREAD

**Issue by ricardoisdebugging** [packdat/SourcetrailDotnetIndexer#8]
Hi, 

Thanks for the provision of this awesome tool firstly! Here is the exception I met. After I put my built source code files and built source-trail-dot-net-indexer project together and run using the command line of `SourcetrailDotnetIndexer.exe -i RobotControlMate.dll -o . -f ^System -fn ^RobotControlMateSDK`, it reminders me there is  an exception:
![截图_20211116052053](https://user-images.githubusercontent.com/33414765/141957763-11480888-aa16-43cd-a298-f5906b7721cb.png)

The catalogue where I put mine built source code and source-trial is like this:
![截图_20211116052205](https://user-images.githubusercontent.com/33414765/141957943-38a56bb7-f491-4bda-8925-ac970026405a.png)

Hope to obtain your help! Many thanks.

Bests,

**Comment by packdat** [comment]
Hi !
The "BadImageFormatException" seen in your screenshot indicates a bitness-issue.
This can happen if you have a 32-bit executable that tries to load a 64-bit dll (or vice versa).
If you want to build the indexer by yourself, you have to compile it explicitly into a 64-bit executable, as it references a native dll that is also compile into a 64-bit dll (the *SourcetrailDB.dll*).

Alternatively, you can use a pre-build version of the indexer from the [Releases](https://github.com/packdat/SourcetrailDotnetIndexer/releases) page.

**Comment by ricardoisdebugging** [comment]
Thanks, packdat, the issue is fixed
